version: '3.8'

services:
  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    container_name: jenkins-master
    restart: unless-stopped
    ports:
      - "${JENKINS_PORT:-8080}:8080"
      - "${JENKINS_AGENT_PORT:-50000}:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins/scripts:/var/jenkins_scripts
      - ./Terraform:/var/jenkins_workspace/Terraform
      - ./results.xml:/var/jenkins_workspace/results.xml
    environment:
      - JENKINS_OPTS=--httpPort=8080
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
      - GIT_USERNAME=${GIT_USERNAME}
      - GIT_PASSWORD=${GIT_PASSWORD}
      - GIT_REPOSITORY_URL=${GIT_REPOSITORY_URL}
      - GIT_BRANCH=${GIT_BRANCH:-main}
      - JENKINS_USER=${JENKINS_USER:-admin}
      - JENKINS_PASSWORD=${JENKINS_PASSWORD:-admin123}
      - PIPELINE_JOB_NAME=${PIPELINE_JOB_NAME:-terraform-pipeline}
      - DEFAULT_ENVIRONMENT=${DEFAULT_ENVIRONMENT:-develop}
    networks:
      - ${DOCKER_NETWORK_NAME:-jenkins-network}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/login"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  agent-terraform:
    build:
      context: ./agent-terraform
      dockerfile: Dockerfile
    container_name: jenkins-agent-terraform
    restart: unless-stopped
    volumes:
      - ./Terraform:/home/jenkins/workspace/Terraform
      - ./agent-terraform/scripts:/home/jenkins/scripts
      - ./results.xml:/home/jenkins/workspace/results.xml
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
      - JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
      - TERRAFORM_VERSION=${TERRAFORM_VERSION:-latest}
      - TERRAFORM_BACKEND_BUCKET=${TERRAFORM_BACKEND_BUCKET}
      - TERRAFORM_BACKEND_KEY=${TERRAFORM_BACKEND_KEY:-terraform.tfstate}
      - TERRAFORM_BACKEND_REGION=${TERRAFORM_BACKEND_REGION:-us-east-1}
      - CHECKOV_SKIP_CHECKS=${CHECKOV_SKIP_CHECKS}
      - CHECKOV_OUTPUT_FORMAT=${CHECKOV_OUTPUT_FORMAT:-cli,junitxml}
      - CHECKOV_OUTPUT_FILE=${CHECKOV_OUTPUT_FILE:-results.xml}
    networks:
      - ${DOCKER_NETWORK_NAME:-jenkins-network}
    depends_on:
      - jenkins
    command: ["tail", "-f", "/dev/null"]  # Mantener el contenedor corriendo

volumes:
  jenkins_home:
    driver: local

networks:
  jenkins-network:
    driver: bridge 