server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: microservicios
    static_configs:
      - targets: [localhost]
        labels:
          job: ms_auth_logs
          __path__: /shared-logs/ms_auth_*.log
      - targets: [localhost]
        labels:
          job: ms_user_logs
          __path__: /shared-logs/ms_user_*.log