version: '3.8'

services:
  grafana:
  image: grafana/grafana:lastest
  ports:
    - "3000:3000"
  volumes:
    - ./grafana/provisioning:/etc/grafana/provisioning
  depends_on:
    - loki

loki:
  image: grafana/loki:2.9.2
  ports:
    - "3100:3100"
  volumes:
    - ./loki/config.yml:/etc/loki/config.yml

promtail:
  image:  grafana/promtail:2.9.2
  volumes:
    - shared-logs:/shared-logs
    - ./promtail/config.yml:/etc/promtail/config.yml
  command: -config.file=/etc/promtail/config.yml